sysLocation    "Melody Garden"
sysContact     "admin@example.com"
agentAddress   udp:0.0.0.0:161
rocommunity    public default -V all
rocommunity    public 127.0.0.1
view all included .1
includeAllDisks 10%
extend temp /bin/bash /usr/local/bin/snmp-temperature.sh
