# Generated by Django 4.2.30 on 2026-06-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CpuPercent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(db_column='time')),
                ('cpu', models.CharField(max_length=16)),
                ('percent', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CPU Percent',
                'verbose_name_plural': 'CPU Percents',
                'db_table': 'cpu_percent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiskIoCounters',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(db_column='time')),
                ('disk', models.CharField(blank=True, max_length=128, null=True)),
                ('read_count', models.BigIntegerField(blank=True, null=True)),
                ('write_count', models.BigIntegerField(blank=True, null=True)),
                ('read_bytes', models.BigIntegerField(blank=True, null=True)),
                ('write_bytes', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Disk IO Counter',
                'verbose_name_plural': 'Disk IO Counters',
                'db_table': 'disk_io_counters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiskUsage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(db_column='time')),
                ('mount', models.CharField(blank=True, max_length=255, null=True)),
                ('device_partition', models.CharField(blank=True, max_length=255, null=True)),
                ('total', models.BigIntegerField(blank=True, null=True)),
                ('used', models.BigIntegerField(blank=True, null=True)),
                ('free', models.BigIntegerField(blank=True, null=True)),
                ('percent', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Disk Usage',
                'verbose_name_plural': 'Disk Usages',
                'db_table': 'disk_usage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoadAvg',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(db_column='time')),
                ('load_1m', models.FloatField(blank=True, null=True)),
                ('load_5m', models.FloatField(blank=True, null=True)),
                ('load_15m', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Load Average',
                'verbose_name_plural': 'Load Averages',
                'db_table': 'load_avg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(db_column='time')),
                ('total', models.BigIntegerField(blank=True, null=True)),
                ('available', models.BigIntegerField(blank=True, null=True)),
                ('used', models.BigIntegerField(blank=True, null=True)),
                ('free', models.BigIntegerField(blank=True, null=True)),
                ('percent', models.FloatField(blank=True, null=True)),
                ('buffers', models.BigIntegerField(blank=True, null=True)),
                ('cached', models.BigIntegerField(blank=True, null=True)),
                ('shared', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Memory',
                'verbose_name_plural': 'Memory Records',
                'db_table': 'memory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NetIoCounters',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(db_column='time')),
                ('if_index', models.IntegerField(blank=True, null=True)),
                ('iface', models.CharField(blank=True, max_length=128, null=True)),
                ('if_high_speed_mbps', models.BigIntegerField(blank=True, null=True)),
                ('if_admin_status', models.IntegerField(blank=True, null=True)),
                ('if_oper_status', models.IntegerField(blank=True, null=True)),
                ('bytes_sent', models.BigIntegerField(blank=True, null=True)),
                ('bytes_recv', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Network IO Counter',
                'verbose_name_plural': 'Network IO Counters',
                'db_table': 'net_io_counters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwapMemory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(db_column='time')),
                ('total', models.BigIntegerField(blank=True, null=True)),
                ('used', models.BigIntegerField(blank=True, null=True)),
                ('free', models.BigIntegerField(blank=True, null=True)),
                ('percent', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Swap Memory',
                'verbose_name_plural': 'Swap Memory Records',
                'db_table': 'swap_memory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(db_column='time')),
                ('sys_location', models.CharField(blank=True, max_length=255, null=True)),
                ('sys_uptime', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'System Info',
                'verbose_name_plural': 'System Info',
                'db_table': 'system_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(db_column='time')),
                ('cpu_temp', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Temperature',
                'verbose_name_plural': 'Temperatures',
                'db_table': 'temperature',
                'managed': False,
            },
        ),
    ]
