# Generated by Django 4.2.30 on 2026-06-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sysname', models.CharField(db_index=True, help_text='System name from SNMP (static identifier)', max_length=255, unique=True)),
                ('ip_address', models.CharField(blank=True, help_text='IPv4 address (may change dynamically)', max_length=15, null=True)),
                ('last_seen', models.DateTimeField(db_column='last_seen', help_text='Last time device was seen online')),
                ('online', models.BooleanField(default=True, help_text='Device online status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'db_table': 'devices',
                'managed': False,
            },
        ),
    ]
